### ISSUE TITLE
Disabling it stops the internet access for clients..

### ISSUE THREAD

**Issue by keldnorman** [Foxtrot/RandomRoll#1]
When i stop the module - all the clients connected end up with the message "403 Forbidden" message from nginx/1.4.7 - i have to reboot the pineapple to get access again

**Comment by Foxtrot** [comment]
Seems to be because the initial index.php isn't being restored.

After you stop the module, what are the contents of /www ?

**Comment by keldnorman** [comment]
root@Pineapple:/www# ls -alrt
drwxr-xr-x    1 root     root           552 Jan  1  1970 ..
drwxrwxr-x    1 root     root           232 Feb 29 13:22 .


2016-02-28 14:36 GMT+01:00 Marc <notifications@github.com>:

> Seems to be because the initial index.php isn't being restored.
>
> After you stop the module, what are the contents of /www ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Foxtrot/RandomRoll/issues/1#issuecomment-189872843>.
>



-- 
Venlig hilsen/Best regards,
Keld Norman

keld.norman@gmail.com

**Comment by keldnorman** [comment]
Ah sorry wrong dir.. here is the right one

root@Pineapple:/overlay/upper/www# ls -al
drwxrwxr-x    2 root     root           232 Feb 29 13:36 .
drwxr-xr-x    8 root     root           552 Jan  1  1970 ..
c---------    1 root     root        0,   0 Feb 29 13:36 index.php


if i delete the index.php ( notice the C--------- ) and recreate it as 555
then everything works again..


2016-02-28 14:36 GMT+01:00 Marc <notifications@github.com>:

> Seems to be because the initial index.php isn't being restored.
>
> After you stop the module, what are the contents of /www ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Foxtrot/RandomRoll/issues/1#issuecomment-189872843>.
>



-- 
Venlig hilsen/Best regards,
Keld Norman

keld.norman@gmail.com

**Comment by Foxtrot** [comment]
The first reply is correct, not the second one...

I will look into this issue when possible.

**Comment by Foxtrot** [comment]
Issue fixed.
